# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import atom_agent_pb2 as proto_dot_atom__agent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/atom_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtomAgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/com.atom.proto.AtomAgentService/Register',
                request_serializer=proto_dot_atom__agent__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/com.atom.proto.AtomAgentService/Login',
                request_serializer=proto_dot_atom__agent__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.AuthenticateWithGoogle = channel.unary_unary(
                '/com.atom.proto.AtomAgentService/AuthenticateWithGoogle',
                request_serializer=proto_dot_atom__agent__pb2.GoogleAuthRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/com.atom.proto.AtomAgentService/RefreshToken',
                request_serializer=proto_dot_atom__agent__pb2.RefreshRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/com.atom.proto.AtomAgentService/ExecuteCommand',
                request_serializer=proto_dot_atom__agent__pb2.CommandRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/com.atom.proto.AtomAgentService/StreamChat',
                request_serializer=proto_dot_atom__agent__pb2.MessageRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/com.atom.proto.AtomAgentService/Transcribe',
                request_serializer=proto_dot_atom__agent__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_stream(
                '/com.atom.proto.AtomAgentService/Synthesize',
                request_serializer=proto_dot_atom__agent__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=proto_dot_atom__agent__pb2.SynthesizeResponse.FromString,
                _registered_method=True)


class AtomAgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """--- Auth (HU-27): these RPCs do NOT require an access token ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateWithGoogle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Conversational AI (Unary call)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Conversational AI (Streaming response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Voice: Speech-to-Text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Voice: Text-to-Speech
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtomAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proto_dot_atom__agent__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_atom__agent__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.AuthResponse.SerializeToString,
            ),
            'AuthenticateWithGoogle': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateWithGoogle,
                    request_deserializer=proto_dot_atom__agent__pb2.GoogleAuthRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.AuthResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=proto_dot_atom__agent__pb2.RefreshRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.AuthResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=proto_dot_atom__agent__pb2.CommandRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.CommandResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=proto_dot_atom__agent__pb2.MessageRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.MessageResponse.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=proto_dot_atom__agent__pb2.TranscribeRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.TranscribeResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=proto_dot_atom__agent__pb2.SynthesizeRequest.FromString,
                    response_serializer=proto_dot_atom__agent__pb2.SynthesizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.atom.proto.AtomAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.atom.proto.AtomAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AtomAgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atom.proto.AtomAgentService/Register',
            proto_dot_atom__agent__pb2.RegisterRequest.SerializeToString,
            proto_dot_atom__agent__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atom.proto.AtomAgentService/Login',
            proto_dot_atom__agent__pb2.LoginRequest.SerializeToString,
            proto_dot_atom__agent__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateWithGoogle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atom.proto.AtomAgentService/AuthenticateWithGoogle',
            proto_dot_atom__agent__pb2.GoogleAuthRequest.SerializeToString,
            proto_dot_atom__agent__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atom.proto.AtomAgentService/RefreshToken',
            proto_dot_atom__agent__pb2.RefreshRequest.SerializeToString,
            proto_dot_atom__agent__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atom.proto.AtomAgentService/ExecuteCommand',
            proto_dot_atom__agent__pb2.CommandRequest.SerializeToString,
            proto_dot_atom__agent__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atom.proto.AtomAgentService/StreamChat',
            proto_dot_atom__agent__pb2.MessageRequest.SerializeToString,
            proto_dot_atom__agent__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atom.proto.AtomAgentService/Transcribe',
            proto_dot_atom__agent__pb2.TranscribeRequest.SerializeToString,
            proto_dot_atom__agent__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atom.proto.AtomAgentService/Synthesize',
            proto_dot_atom__agent__pb2.SynthesizeRequest.SerializeToString,
            proto_dot_atom__agent__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
